on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://ayush1609:$HF_TOKEN@huggingface.co/spaces/ayush1609/AI-Financial-Analyst
          git filter-branch --force --index-filter \
            'git rm -r --cached --ignore-unmatch Screenshots/' \
            --prune-empty --tag-name-filter cat -- --all
          git push hf main --force